# Generated by Django 5.0.6 on 2025-04-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='next_skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
